export const sprueche = [
    "Das Reh springt hoch, das Reh springt weit, warum auch nicht, es hat ja Zeit!",
    "Der Glatzkopf der die Glatze föhnt, hat mit dem Schicksal sich versöhnt.",
    "Der See lädt ein zum Bade...ausgetrocknet...Schade.",
    "Verweile nicht in der Vergangenheit, träume nicht von der Zukunft. Konzentriere dich auf den gegenwärtigen Moment.",
    "Wir denken selten an das, was wir haben, aber immer an das, was uns fehlt.",
    "Du siehst die Welt nicht so wie sie ist, du siehst die Welt so wie du bist.",
    "Alle Menschen, die man lange im Vorzimmer seiner Gunst stehen läßt, geraten in Gärung oder werden sauer.",
    "Der Philosoph glaubt, der Wert seiner Philosophie liege im Ganzen, im Bau: die Nachwelt findet ihn im Stein, mit dem er baute und mit dem, von da an, noch oft und besser gebaut wird: also darin, daß jener Bau zerstört werden kann und doch noch als Material Wert hat.",
    "Wo ich Lebendiges fand, da fand ich Willen zur Macht; und noch im Willen des Dienenden fand ich den Willen, Herr zu sein.",
    "Was du mir sagst, das vergesse ich. Was du mir zeigst, daran erinnere ich mich. Was du mich tun lässt, das verstehe ich.",
    "Wo ist das verdammte Geld, Lebowski ? Wo ist das verdammte Geld, du Drecksack?",
    "Ohne Handeln sind die besten Absichten in der Welt nichts weiter als das: Absichten.",
    "Die einzige Sache, die zwischen dir und deinem Ziel steht, sind die Bullshit Ausreden, die du dir ständig selbst erzählst.",
    "Die Tatsache, dass auf Euren Waffen klar und deutlich 'Replica' steht, und auf meiner 'Desert Eagle 0,50' sollte euch zu denken geben.",
    "Gerne der Zeiten gedenk' ich, da alle Glieder gelenkig - bis auf eins. Doch die Zeiten sind vorüber, steif geworden alle Glieder - bis auf eins.",
    "Weisheit stellt sich nicht immer mit dem Alter ein. Manchmal kommt auch das Alter ganz allein.",
    "Geliebt wirst du einzig, wo du schwach dich zeigen darfst, ohne Stärke zu provozieren.",
    "Stärke wächst nicht aus körperlicher Kraft - vielmehr aus unbeugsamen Willen.",
    "Man will nicht nur glücklich sein, sondern glücklicher als die anderen. Und das ist deshalb so schwer, weil wir die anderen für glücklicher halten, als sie sind.",
    "Mut ist, wenn man Todesangst hat, aber sich trotzdem in den Sattel schwingt.",
    "Die Frau kontrolliert ihren Sex, weil sie für Sex all das bekommt, was ihr noch wichtiger ist als Sex.",
    "Wer lachen kann, dort wo er hätte heulen können, bekommt wieder Lust zu Leben.",
    "Eigentlich wollte ich dir schenken eine Torte. Doch ich kann leider nicht backen. Darum gibt es nur nette Worte.",
    "Vertrauen ist wie Papier. Wenn man es einmal zerknüllt, wird es nie wieder perfekt.",
    "Folge deinem Herzen, aber nimm dein Hirn mit.",
    "Sobald du anfängst, dir Gedanken darüber zu machen, was Andere über dich denken, hörst du auf, du selbst zu sein.",
    '"Wie trinkst du deinen Kaffee?" "Müde."',
    "Bist du traurig, hast du Sorgen, soll ich dir mein Lächeln borgen? Nutz es gut, es bringt dir Glück und wenn du`s nicht mehr brauchst, gib`s mir irgendwann zurück.",
    "Wer will findet Wege, wer nicht will, der findet Gründe.",
    "Alle sagten: Das geht nicht. Dann kam einer, der wusste das nicht und hat's gemacht.",
    "Manche Menschen wollen immer nur glänzen, obwohl sie keinen Schimmer haben.",
    "Das erste, was man bei einer Abmagerungskur verliert, ist die gute Laune.",
    "Bei manchen Menschen geht alles schnell zum einen Ohr rein und zum anderen raus - die haben auch nicht viel dazwischen.",
    "Das Lernen macht stets dann Verdruß’, wenn man’s nicht will, es aber muß.",
    "Ich brauche nur Fettgedrucktes zu lesen, schon nehme ich zu.",
    "Paradox ist, wenn einer sich im Handumdrehen den Fuß bricht.",
    "Liebschaften sind wie Pilzgerichte, ob sie ungefährlich waren, weiß man erst später.",
    "Pessimisten sind Leute, die mit der Sonnenbrille in die Zukunft schauen.",
    "Der schläft gut, der nicht weiß, wie schlecht er schläft.",
    "Will jemand eine Jungfrau frein, darf er nicht penibel sein.",
    "Was du liebst, lass frei. Kommt es zurück, gehört es dir - für immer.",
    "Fordere viel von dir selbst und erwarte wenig von anderen. So wird dir viel Ärger erspart bleiben.",
    "Sage es mir, und ich vergesse es. Zeige es mir, und ich erinnere mich. Lass es mich tun, und ich behalte es.",
    "Falls du glaubst, dass du zu klein bist, um etwas zu bewirken, dann versuche mal zu schlafen, wenn eine Mücke im Raum ist.",
    "In der Wut verliert der Mensch seine Intelligenz.",
    "Denke daran, dass etwas, was du nicht bekommst, manchmal eine wunderbare Fügung des Schicksals sein kann.",
    "Denke daran, dass Schweigen manchmal die beste Antwort ist.",
    "Jede schwierige Situation, die du jetzt meisterst, bleibt dir in der Zukunft erspart.",
    "Lasse das Verhalten anderer nicht deinen inneren Frieden stören.",
    "Die Ironie will es so, dass wir dann, wenn wir das Objekt unserer Wünsche erlangt haben, immer noch nicht zufrieden sind. Auf diese Weise nimmt die Begierde nie ein Ende und ist eine ständige Quelle der Schwierigkeiten. Das einzige Gegenmittel ist die Genügsamkeit.",
    "Wir leben nicht, um zu glauben, sondern um zu lernen.",
    "Besuche einmal im Jahr einen Ort, den du noch nicht kennst.",
    "Die Übung in Geduld bewahrt uns vor dem Verlust unserer Gelassenheit. Dadurch haben wir die Möglichkeit unser Urteilsvermögen zu trainieren, selbst in sehr schwierigen Situationen. Es gibt uns inneren Raum. Und durch diesen Raum gewinnen wir ein gewisses Maß an Selbstbeherrschung, welche uns erlaubt auf Situationen in angemessener Weise reagieren zu können. Mitfühlend, anstatt durch unsere Wut und Verärgerung getrieben.",
    "Ziele erreichen ist wie Bergsteigen, es zieht anfangs Energie und gibt sie dann um ein Vielfaches zurück.",
    "Fokus ist die ausnahmslose Bündelung der Kräfte auf eine Sache.",
    "Menschen bewegen sich, sobald Licht, Hitze und Timing im Einklang sind.",
    "Jeder Abend ist die letzte Chance, jeder Morgen ein neuer Anfang.",
    "Ist etwas zerronnen, ist es aus anderer Sicht vielleicht gewonnen.",
    "Ein Vorurteil wird immer nur ein Teil vom Ganzen sein.",
    "Wenn du kritisiert wirst, dann musst du irgend etwas richtig machen. Denn man greift nur denjenigen an, der den Ball hat.",
    "Besser langsam und richtig als schnell und falsch.",
    "Ich fürchte nicht den Mann, der 10.000 Kicks einmal geübt hat, aber ich fürchte mich vor dem, der einen Kick 10.000 mal geübt hat.",
    "Der Wille gestaltet den Menschen, zum Erfolg braucht der jedoch Mut und Ausdauer.",
    "Eine wahrhafte Anstrengung in die Richtung eines bestimmten Zieles, gibt dem Leben Sinn und Zweck.",
    "Am meisten über einen Menschen sagt nicht aus, wie er mit Freunden umgeht, sondern mit Fremden.",
    "Geh deinen Weg und lass die Leute reden!",
    "Des is wia bei jeda Wissenschaft, am Schluss stellt sich dann heraus, dass alles ganz anders war.",
    "Jedes Ding hat drei Seiten, eine positive, eine negative und eine komische.",
    "Als ich das Licht der Welt und sodann die Hebamme erblickte, war ich sprachlos. Ich hatte diese Frau ja noch nie in meinem Leben gesehen.",
    "Kunst ist schön, macht aber viel Arbeit.",
    "Gut, dass Hitler nicht Kräuter heißt, sonst müsste man ihn mit 'Heil Kräuter' grüßen.",
    "Wer von seinem Tag nicht zwei Drittel für sich selbst hat, ist ein Sklave.",
    "Wir sind so gerne in der freien Natur, weil diese keine Meinung über uns hat.",
    "Die Hoffnung ist der Regenbogen über den herabstürzenden Bach des Lebens.",
    "Überzeugungen sind gefährlichere Feinde der Wahrheit als Lügen.",
    "Wenn man ein Wozu des Lebens hat, erträgt man jedes Wie.",
    "Hast du eine große Freude an etwas gehabt, so nimm Abschied! Nie kommt es zum zweiten Male.",
    "Toleranz ist ein Beweis des Mißtrauens gegen ein eigenes Ideal.",
    "Es ist leichter, einer Begierde ganz zu entsagen, als in ihr maßzuhalten.",
    "Viele sind hartnäckig in Bezug auf den einmal eingeschlagenen Weg, wenige in Bezug auf das Ziel.",
    "Dem wird befohlen, der sich nicht selber gehorchen kann.",
    "Wünschen ist ein Anzeichen von Genesung oder Besserung.",
    "Die Wissenschaft nötigt uns, den Glauben an einfache Kausalitäten aufzugeben.",
    "Wenn du lange in einen Abgrund blickst, blickt der Abgrund auch in dich hinein.",
    "Niemand rettet uns, außer wir selbst. Niemand kann und niemand darf das. Wir müssen selbst den Weg gehen.",
    "Zuerst wird man für dumm gehalten. Dann ist man ein Lügner.",
    "That's life (That's life), that's life and I can't deny it; Many times I thought of cutting out but my heart won't buy it; But if there's nothing shaking come this here July; I'm gonna roll myself up in a big ball and die; My, my",
    "Wer etwas ändern will, sollte wissen wo er steht.",
    "10% sind besser als gar nichts.",
    "Komplimente sind wie ungedeckte Schecks. Will man sie einlösen, platzen sie.",
    'Altruistische Verhaltensweisen wurden – mit Hilfe der jeweils gewählten Begriffsdefinition bzw. erdachten Interpretation – bei Menschen und verschiedenen Tierarten „nachgewiesen“;[7][3] eine 2009 publizierte Studie schreibt Altruismus auch Pflanzen zu,[8] und 2010 wurde in der Zeitschrift Nature altruistisches Verhalten bei Bakterien beschrieben.[9]',
    "Eine Seefahrt unterscheidet sich von einer schönen Seefahrt dadurch, dass man der einen ihr baldiges Ende herbeiwünscht und der anderen, dass sie nicht enden möge.",
	"First you are taken for a fool. Then you are a liar.",
	"Man kann nur die Dinge tun, die man selber will.",
	"The imperfection of the present is the opportunity for the future.",
	"It's possibly good, if people listen to you, to sometimes talk crap so that people always verify what you're saying.",
]